import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import personDesktop from '../assets/images/hero-desktop.jpg';
import personMobile from '../assets/images/hero-mobile.jpg';
import logo from '../assets/images/logo.svg';
import arrow from '../assets/images/icon-arrow.svg';
import { useMediaQuery } from 'react-responsive';

export default function Home()
{
  const isMobile = useMediaQuery({ query: '(max-width: 1000px)' });
  return (
    <main>
      <Head>
        <title>Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <div className={styles.main_container}>
        <div className={styles.content_container}>
        <div className={styles.logo_container}><Image src={logo} alt="website Logo" layout='fill' /></div>
          <div className={styles.text_container}>
            <h1>
              WE&apos;RE<br/> <strong>COMING SOON</strong>
            </h1>
            <p>
              Hello fellow shoppers!, We&apos;re currently building our new fashion store. add your email below to stay up-to-date with announcement and our launch deals.
            </p>
            <div>
              <input type='email' placeholder='Email Address...' />
              <div className={styles.arrow_container}><Image src={arrow} alt="arrow img" width={20} height={20} /></div>
            </div>
          </div>
        </div>
        <div className={styles.img_container}><Image src={isMobile ? personMobile : personDesktop} alt="person Photo" layout='fill' /></div>
      </div>
    </main>
  )
}
